/** Copy for the checkout feature. */

export const CHECKOUT_COPY = {
  TITLE: "Checkout",
  DELIVERY: "Delivery",
  PICKUP: "Pickup",
  DELIVERY_ADDRESS: "Delivery address",
  ADD_ADDRESS: "Add address",
  NO_ADDRESSES: "No saved addresses yet — add one to continue.",
  WHEN: "When do you need it?",
  SLOT: "Pick a time slot",
  CHOOSE_TIME: "Choose date & time",
  ANY_TIME: "Any time that day",
  SCHEDULE_TITLE: "Delivery time",
  SCHEDULE_DONE: "Set time",
  NO_SLOTS: "No slots left on this day — try another date.",
  NO_DATES: "This branch has no bookable dates right now.",
  PAYMENT: "Payment",
  COD_DELIVERY: "Cash on delivery",
  COD_PICKUP: "Pay at store",
  UPI: "UPI (pay to shop)",
  COUPON: "Coupons & offers",
  COUPON_SHEET_TITLE: "Coupons & offers",
  VIEW_COUPONS: "View available coupons",
  NO_COUPONS: "No offers available right now.",
  MIN_ORDER_NOTE: "on orders above",
  COUPON_PLACEHOLDER: "Enter coupon code",
  APPLY: "Apply",
  REMOVE: "Remove",
  COUPON_INVALID: "This coupon can't be applied",
  COUPON_APPLIED: "applied!",
  CHANGE_OFFER: "Change offer",
  TOTAL_SAVINGS: "Your total savings",
  SAVED: "Saved",
  BILL: "Bill details",
  SUBTOTAL: "Item total",
  DISCOUNT: "Coupon discount",
  TOTAL: "To pay",
  PLACE_ORDER: "Place Order",
  ORDER_SUCCESS: "Order placed 🎉",
  // Confirmation sheet
  CONFIRM_TITLE: "Confirm your order",
  CONFIRM_ITEMS: "Items",
  CONFIRM_SCHEDULE: "Scheduled for",
  CONFIRM_PAYMENT: "Paying by",
  CONFIRM_CTA: "Confirm & place order",
  CONFIRM_BACK: "Review again",
  // Success screen
  SUCCESS_TITLE: "Order placed!",
  SUCCESS_DESC:
    "The bakery has your order and will start on it soon. Track it live from the home screen.",
  // Address form
  ADDRESS_TITLE: "Enter complete address",
  SAVE_AS: "Save address as",
  LABEL: "Custom label (e.g. Grandma's)",
  FULL_ADDRESS: "Full address",
  LANDMARK: "Landmark",
  CITY: "City",
  PINCODE: "Pincode",
  MAKE_DEFAULT: "Make default",
  SAVE_ADDRESS: "Save address",
} as const;

/** Quick "save address as" choices (Blinkit-style); Other reveals a custom label. */
export const ADDRESS_LABELS = ["Home", "Work", "Hotel", "Other"] as const;
